#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Oct 03, 2025 08:01:29 AM CDT  platform: Linux
#    Oct 03, 2025 09:02:50 AM CDT  platform: Linux
#    Oct 03, 2025 09:05:36 AM CDT  platform: Linux
#    Oct 03, 2025 10:37:16 AM CDT  platform: Linux

import sys

import tkEditor1

import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
from tkinter import font
import tkinter.messagebox as messagebox
from tkinter import simpledialog
from tkinter import colorchooser
from tkinter.filedialog import (
    askdirectory,
    askopenfilename,
    asksaveasfile,
    asksaveasfilename,
)
from tkinter.simpledialog import askfloat, askinteger, askstring

import tkEditorDemo1

_debug = True  # False to eliminate debug printing from callback functions.
location = tkEditorDemo1._location
programName = "PyEditor"
version = "0.1.0"


def main(*args):
    """Main entry point for the application."""
    global root
    root = tk.Tk()
    root.protocol("WM_DELETE_WINDOW", root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = tkEditorDemo1.Toplevel1(_top1)
    startup()
    root.mainloop()


def startup():
    _w1.frameAbout.lower()
    global ed1
    pyed = tkEditor1.PyEditor
    ed1 = pyed(_w1.frameEd1)
    # ed1.clear_editor()
    # ed1.load_file("pyScrolledText15.py")
    _top1.title(f"{programName} - {version}")
    libVer = ed1.get_version()
    libLic = ed1.get_licence()
    print(f"{libVer=}")
    print(f"{libLic=}")
    global current_filename
    current_filename = ""


def on_btnClear(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnClear")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    ed1.clear_editor()


def on_btnExit(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnExit")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    sys.exit()


def on_btnFileNew(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnFileNew")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    global current_filename
    current_filename = ""


def on_btnFileOpen(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnFileOpen")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    global ed1, current_filename
    if _debug:
        print("pyed2a_support.on_btnFileOpen")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    filename = askopenfilename(
        initialdir=location,
        title="Select A File",
        parent=_top1,
        filetypes=(
            ("Python files", "*.py"),
            ("ttd files", "*.ttd"),
            ("text files", "*.txt"),
            ("Any Files", "*.*"),
        ),
    )
    # print(filename)
    if filename != ():
        if filename != "":
            print(f"{filename}")
            # return filename
            ed1.clear_editor()
            ed1.load_file(filename)
            current_filename = filename

    _top1.title(f"{programName} - {version} - {current_filename}")


def on_btnFileSave(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnFileSave")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    global current_filename
    contents = ed1.text.get(1.0, END)
    if current_filename == "":
        # ask filename and location
        file_path = asksaveasfilename(
            defaultextension=".txt",
            filetypes=[
                ("Python files", "*.py"),
                ("Text files", "*.txt"),
                ("All files", "*.*"),
            ],
            initialdir=location,  # Optional: set initial directory
            title="Save your file",  # Optional: set dialog title
        )
        if file_path:
            # User selected a file path, now you can write data to it
            with open(file_path, "w") as f:
                f.write(contents)
            print(f"File saved to: {file_path}")
            _top1.title(f"{programName} - {version} - {current_filename} - Saved")

        else:
            print("Save operation cancelled.")
    else:
        with open(current_filename, "w") as f:
            f.write(contents)
        print(f"File Write complete")
    _top1.title(f"{programName} - {version} - {current_filename} - Saved")


def write_file(filename, strng):
    with open(filename, "w") as f:
        f.write(strng)


def read_file(filename):
    # ======================================================
    # function read_file()
    # ======================================================
    # Read file, leaving end of lines
    # ======================================================
    with open(filename) as f:
        lines = f.read()
    return lines


def on_bthAbout(*args):
    if _debug:
        print("tkEditorDemo1_support.on_bthAbout")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    _w1.frameAbout.lift()


def on_btnHelp(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnHelp")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    titl = f"{programName}"
    msg = "Sorry, but the help fucntion is still under development."
    parent = _top1
    ico = messagebox.INFO
    messagebox.showinfo(titl, msg, parent=parent, icon=ico)


def on_btnAboutDismiss(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnAboutDismiss")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    _w1.frameAbout.lower()


def on_btnFileSaveAs(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnFileSaveAs")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    current_filename = ""
    contents = ed1.text.get(1.0, END)
    if current_filename == "":
        # ask filename and location
        file_path = asksaveasfilename(
            defaultextension=".txt",
            filetypes=[
                ("Python files", "*.py"),
                ("Text files", "*.txt"),
                ("All files", "*.*"),
            ],
            initialdir=location,  # Optional: set initial directory
            title="Save your file",  # Optional: set dialog title
        )
        if file_path:
            # User selected a file path, now you can write data to it
            with open(file_path, "w") as f:
                f.write(contents)
            print(f"File saved to: {file_path}")
        else:
            print("Save operation cancelled.")
    else:
        with open(current_filename, "w") as f:
            f.write(contents)
        print(f"File Write complete")


if __name__ == "__main__":
    tkEditorDemo1.start_up()
