#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Oct 07, 2025 03:29:04 AM CDT  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import tkEditorDemo1_support

_bgcolor = '#a2a2a2'
_fgcolor = 'black'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

_style_code_ran = 0
def _style_code():
    global _style_code_ran
    if _style_code_ran: return        
    try: tkEditorDemo1_support.root.tk.call('source',
                os.path.join(_location, 'themes', 'notasdark.tcl'))
    except: pass
    style = ttk.Style()
    style.theme_use('notasdark')
    style.configure('.', font = "TkDefaultFont")
    _style_code_ran = 1

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("1134x845+745+342")
        top.minsize(1, 1)
        top.maxsize(4465, 1410)
        top.resizable(0,  0)
        top.title("Toplevel 0")
        top.configure(background="#a2a2a2")
        top.configure(highlightbackground="#a2a2a2")
        top.configure(highlightcolor="black")

        self.top = top
        self.StatusInfo1 = tk.StringVar()
        self.StatusInfo2 = tk.StringVar()
        self.StatusTime = tk.StringVar()
        self.kwdColorData = tk.StringVar()
        self.kwdColorData.set('TEntry')
        self.stringColorData = tk.StringVar()
        self.stringColorData.set('TEntry')
        self.stringLabelTest = tk.StringVar()
        self.KwdLabelTest = tk.StringVar()
        self.commentColourData = tk.StringVar()
        self.commentColourData.set('TEntry')
        self.CommentLabelTest = tk.StringVar()
        self.LineBgColorData = tk.StringVar()
        self.LineBgColorData.set('TEntry')
        self.LineColorLabelTest = tk.StringVar()
        self.EditorBgColorData = tk.StringVar()
        self.EditorBgColorData.set('TEntry')
        self.EditorLabelColorTest = tk.StringVar()
        self.IndentData = tk.StringVar()
        self.IndentData.set('TEntry')

        _style_code()
        self.frameStatus = ttk.Frame(self.top)
        self.frameStatus.place(x=1, y=790, height=50, width=1130)
        self.frameStatus.configure(relief='sunken')
        self.frameStatus.configure(borderwidth="2")
        self.frameStatus.configure(relief="sunken")

        self.lblStatusInfo1 = ttk.Label(self.frameStatus)
        self.lblStatusInfo1.place(x=3, y=3, height=43, width=524)
        self.lblStatusInfo1.configure(font="-family {DejaVu Sans} -size 11 -weight bold")
        self.lblStatusInfo1.configure(relief="sunken")
        self.lblStatusInfo1.configure(textvariable=self.StatusInfo1)
        self.lblStatusInfo1.configure(compound='left')
        self.lblStatusInfo1.configure(cursor="arrow")

        self.lblStatusInfo2 = ttk.Label(self.frameStatus)
        self.lblStatusInfo2.place(x=529, y=3, height=43, width=458)
        self.lblStatusInfo2.configure(font="-family {DejaVu Sans} -size 11 -weight bold")
        self.lblStatusInfo2.configure(relief="sunken")
        self.lblStatusInfo2.configure(textvariable=self.StatusInfo2)
        self.lblStatusInfo2.configure(compound='left')
        self.lblStatusInfo2.configure(cursor="arrow")

        self.lblStatusTime = ttk.Label(self.frameStatus)
        self.lblStatusTime.place(x=990, y=3, height=43, width=134)
        self.lblStatusTime.configure(font="-family {DejaVu Sans} -size 14 -weight bold")
        self.lblStatusTime.configure(relief="sunken")
        self.lblStatusTime.configure(anchor='center')
        self.lblStatusTime.configure(textvariable=self.StatusTime)
        self.lblStatusTime.configure(compound='left')
        self.lblStatusTime.configure(cursor="arrow")

        self.frameMain = ttk.Frame(self.top)
        self.frameMain.place(x=0, y=51, height=739, width=1130)
        self.frameMain.configure(relief='sunken')
        self.frameMain.configure(borderwidth="2")
        self.frameMain.configure(relief="sunken")

        self.TNotebook1 = ttk.Notebook(self.frameMain)
        self.TNotebook1.place(x=6, y=3, height=733, width=1114)
        self.TNotebook1.configure(cursor="arrow")
        self.TNotebook1_t1 = tk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t1, padding=3)
        self.TNotebook1.tab(0, text="Page 1",compound="left",)
        self.TNotebook1_t1.configure(background="#a2a2a2")
        self.TNotebook1_t1.configure(cursor="arrow")
        self.TNotebook1_t1.configure(highlightbackground="#a2a2a2")
        self.TNotebook1_t2 = tk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t2, padding=3)
        self.TNotebook1.tab(1, text="Page 2",compound="left",)
        self.TNotebook1_t2.configure(background="#a2a2a2")
        self.TNotebook1_t2.configure(cursor="arrow")
        self.TNotebook1_t2.configure(highlightbackground="#a2a2a2")

        self.frameEd1 = ttk.Frame(self.TNotebook1_t1)
        self.frameEd1.place(x=4, y=4, height=685, width=1102)
        self.frameEd1.configure(relief='sunken')
        self.frameEd1.configure(borderwidth="2")
        self.frameEd1.configure(relief="sunken")
        self.frameEd1.configure(cursor="arrow")

        self.frameEd2 = ttk.Frame(self.TNotebook1_t2)
        self.frameEd2.place(x=4, y=4, height=685, width=1102)
        self.frameEd2.configure(relief='sunken')
        self.frameEd2.configure(borderwidth="2")
        self.frameEd2.configure(relief="sunken")
        self.frameEd2.configure(cursor="arrow")

        self.frameButtons = ttk.Frame(self.top)
        self.frameButtons.place(x=1, y=1, height=50, width=1130)
        self.frameButtons.configure(relief='sunken')
        self.frameButtons.configure(borderwidth="2")
        self.frameButtons.configure(relief="sunken")
        self.frameButtons.configure(cursor="arrow")

        self.btnExit = ttk.Button(self.frameButtons)
        self.btnExit.place(x=1081, y=2, height=42, width=42)
        self.btnExit.configure(command=tkEditorDemo1_support.on_btnExit)
        photo_location = os.path.join(_location,"./graphics/system-shutdown.png")
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.btnExit.configure(image=_img0)
        self.btnExit.configure(compound='left')
        self.btnExit.configure(style='Toolbutton')
        self.btnExit_tooltip = \
        ToolTip(self.btnExit, '''Exit''')

        self.btnHelp = ttk.Button(self.frameButtons)
        self.btnHelp.place(x=1026, y=3, height=42, width=42)
        self.btnHelp.configure(command=tkEditorDemo1_support.on_btnHelp)
        photo_location = os.path.join(_location,"./graphics/question.png")
        global _img1
        _img1 = tk.PhotoImage(file=photo_location)
        self.btnHelp.configure(image=_img1)
        self.btnHelp.configure(compound='left')
        self.btnHelp.configure(style='Toolbutton')
        self.btnHelp_tooltip = \
        ToolTip(self.btnHelp, '''Help''')

        self.btnAbout = ttk.Button(self.frameButtons)
        self.btnAbout.place(x=982, y=3, height=42, width=42)
        self.btnAbout.configure(command=tkEditorDemo1_support.on_bthAbout)
        photo_location = os.path.join(_location,"./graphics/information.png")
        global _img2
        _img2 = tk.PhotoImage(file=photo_location)
        self.btnAbout.configure(image=_img2)
        self.btnAbout.configure(compound='left')
        self.btnAbout.configure(style='Toolbutton')
        self.btnAbout_tooltip = \
        ToolTip(self.btnAbout, '''About the program''')

        self.btnFileSave = ttk.Button(self.frameButtons)
        self.btnFileSave.place(x=106, y=3, height=42, width=42)
        self.btnFileSave.configure(command=tkEditorDemo1_support.on_btnFileSave)
        photo_location = os.path.join(_location,"./graphics/document-save.png")
        global _img3
        _img3 = tk.PhotoImage(file=photo_location)
        self.btnFileSave.configure(image=_img3)
        self.btnFileSave.configure(compound='left')
        self.btnFileSave.configure(style='Toolbutton')
        self.btnFileSave_tooltip = \
        ToolTip(self.btnFileSave, '''Save the current file''')

        self.btnFileOpen = ttk.Button(self.frameButtons)
        self.btnFileOpen.place(x=58, y=3, height=42, width=42)
        self.btnFileOpen.configure(command=tkEditorDemo1_support.on_btnFileOpen)
        photo_location = os.path.join(_location,"./graphics/document-open.png")
        global _img4
        _img4 = tk.PhotoImage(file=photo_location)
        self.btnFileOpen.configure(image=_img4)
        self.btnFileOpen.configure(compound='left')
        self.btnFileOpen.configure(style='Toolbutton')
        self.btnFileOpen_tooltip = \
        ToolTip(self.btnFileOpen, '''Open File''')

        self.btnClear = ttk.Button(self.frameButtons)
        self.btnClear.place(x=200, y=3, height=42, width=42)
        self.btnClear.configure(command=tkEditorDemo1_support.on_btnClear)
        photo_location = os.path.join(_location,"./graphics/edit-clear.png")
        global _img5
        _img5 = tk.PhotoImage(file=photo_location)
        self.btnClear.configure(image=_img5)
        self.btnClear.configure(compound='left')
        self.btnClear.configure(style='Toolbutton')
        self.btnClear_tooltip = \
        ToolTip(self.btnClear, '''Clear the Editor''')

        self.btnFileNew = ttk.Button(self.frameButtons)
        self.btnFileNew.place(x=10, y=3, height=42, width=42)
        self.btnFileNew.configure(command=tkEditorDemo1_support.on_btnFileNew)
        photo_location = os.path.join(_location,"./graphics/document-new.png")
        global _img6
        _img6 = tk.PhotoImage(file=photo_location)
        self.btnFileNew.configure(image=_img6)
        self.btnFileNew.configure(compound='left')
        self.btnFileNew.configure(style='Toolbutton')
        self.btnFileNew_tooltip = \
        ToolTip(self.btnFileNew, '''Create a NEW file''')

        self.btnFileSaveAs = ttk.Button(self.frameButtons)
        self.btnFileSaveAs.place(x=153, y=3, height=42, width=42)
        self.btnFileSaveAs.configure(command=tkEditorDemo1_support.on_btnFileSaveAs)
        photo_location = os.path.join(_location,"./graphics/document-save-as.png")
        global _img7
        _img7 = tk.PhotoImage(file=photo_location)
        self.btnFileSaveAs.configure(image=_img7)
        self.btnFileSaveAs.configure(compound='left')
        self.btnFileSaveAs.configure(style='Toolbutton')
        self.btnFileSaveAs_tooltip = \
        ToolTip(self.btnFileSaveAs, '''Save Current File As....''')

        self.btnPrefs = ttk.Button(self.frameButtons)
        self.btnPrefs.place(x=898, y=3, height=42, width=42)
        self.btnPrefs.configure(command=tkEditorDemo1_support.on_btnPrefs)
        photo_location = os.path.join(_location,"./graphics/applications-system.png")
        global _img8
        _img8 = tk.PhotoImage(file=photo_location)
        self.btnPrefs.configure(image=_img8)
        self.btnPrefs.configure(compound='left')
        self.btnPrefs.configure(style='Toolbutton')
        self.btnPrefs_tooltip = \
        ToolTip(self.btnPrefs, '''Preferences''')

        self.btnAddTab = ttk.Button(self.frameButtons)
        self.btnAddTab.place(x=530, y=3, height=42, width=42)
        self.btnAddTab.configure(command=tkEditorDemo1_support.on_btnAddTab)
        self.btnAddTab.configure(takefocus="")
        self.btnAddTab.configure(text='''Tbutton''')
        photo_location = os.path.join(_location,"./graphics/list-add.png")
        global _img9
        _img9 = tk.PhotoImage(file=photo_location)
        self.btnAddTab.configure(image=_img9)
        self.btnAddTab.configure(compound='left')
        self.btnAddTab.configure(style='Toolbutton')

        self.frameAbout = ttk.Frame(self.top)
        self.frameAbout.place(x=3, y=53, height=735, width=1125)
        self.frameAbout.configure(relief='sunken')
        self.frameAbout.configure(borderwidth="2")
        self.frameAbout.configure(relief="sunken")
        self.frameAbout.configure(cursor="arrow")

        self.TLabel1 = ttk.Label(self.frameAbout)
        self.TLabel1.place(x=927, y=270, height=251, width=183)
        self.TLabel1.configure(font="TkDefaultFont")
        self.TLabel1.configure(relief="flat")
        photo_location = os.path.join(_location,"./graphics/computergeek transback.175x247.png")
        global _img10
        _img10 = tk.PhotoImage(file=photo_location)
        self.TLabel1.configure(image=_img10)
        self.TLabel1.configure(compound='left')

        self.btmAboutDismiss = ttk.Button(self.frameAbout)
        self.btmAboutDismiss.place(x=490, y=680, height=39, width=148)
        self.btmAboutDismiss.configure(command=tkEditorDemo1_support.on_btnAboutDismiss)
        self.btmAboutDismiss.configure(text='''Dismiss''')
        self.btmAboutDismiss.configure(compound='left')
        self.btmAboutDismiss.configure(style='bold.TButton')

        self.TLabel3 = ttk.Label(self.frameAbout)
        self.TLabel3.place(x=165, y=100, height=83, width=790)
        self.TLabel3.configure(font="-family {Noto Sans} -size 14 -weight bold")
        self.TLabel3.configure(relief="flat")
        self.TLabel3.configure(anchor='center')
        self.TLabel3.configure(text='''Copyright © 2025, 2026 by Greg Walters and Designated Geek Software''')
        self.TLabel3.configure(compound='left')

        self.TLabel2 = ttk.Label(self.frameAbout)
        self.TLabel2.place(x=395, y=40, height=53, width=330)
        self.TLabel2.configure(font="-family {Noto Sans} -size 14 -weight bold")
        self.TLabel2.configure(relief="flat")
        self.TLabel2.configure(anchor='center')
        self.TLabel2.configure(text='''About tkEditorDemo1''')
        self.TLabel2.configure(compound='left')
        self.TLabel2.configure(cursor="fleur")

        self.TFrame2 = ttk.Frame(self.frameAbout)
        self.TFrame2.place(x=197, y=229, height=425, width=725)
        self.TFrame2.configure(relief='groove')
        self.TFrame2.configure(borderwidth="2")
        self.TFrame2.configure(relief="groove")

        self.stAbout = ScrolledText(self.TFrame2)
        self.stAbout.place(x=1, y=2, height=422, width=722)
        self.stAbout.configure(background="white")
        self.stAbout.configure(exportselection="0")
        self.stAbout.configure(font="TkTextFont")
        self.stAbout.configure(highlightbackground="#a2a2a2")
        self.stAbout.configure(insertborderwidth="3")
        self.stAbout.configure(selectbackground="#d9d9d9")
        self.stAbout.configure(wrap="word")

        self.framePrefs = ttk.Frame(self.top)
        self.framePrefs.place(x=3, y=53, height=735, width=1125)
        self.framePrefs.configure(relief='sunken')
        self.framePrefs.configure(borderwidth="2")
        self.framePrefs.configure(relief="sunken")
        self.framePrefs.configure(cursor="arrow")

        self.btnPrefsDismiss = ttk.Button(self.framePrefs)
        self.btnPrefsDismiss.place(x=473, y=650, height=39, width=178)
        self.btnPrefsDismiss.configure(command=tkEditorDemo1_support.on_btnPrefDismiss)
        self.btnPrefsDismiss.configure(text='''Dismiss''')
        self.btnPrefsDismiss.configure(compound='left')
        self.btnPrefsDismiss.configure(style='bold.TButton')

        self.btnPrefsSaveChanges = ttk.Button(self.framePrefs)
        self.btnPrefsSaveChanges.place(x=940, y=70, height=29, width=148)
        self.btnPrefsSaveChanges.configure(command=tkEditorDemo1_support.on_btnPrefsSaveChanges)
        self.btnPrefsSaveChanges.configure(text='''Save Changes''')
        self.btnPrefsSaveChanges.configure(compound='left')

        self.btnPrefsIgnoreChanges = ttk.Button(self.framePrefs)
        self.btnPrefsIgnoreChanges.place(x=940, y=120, height=29, width=148)
        self.btnPrefsIgnoreChanges.configure(command=tkEditorDemo1_support.on_btnPrefsIgnoreChanges)
        self.btnPrefsIgnoreChanges.configure(text='''Ignore Changes''')
        self.btnPrefsIgnoreChanges.configure(compound='left')

        self.TLabelframe1 = ttk.Labelframe(self.framePrefs)
        self.TLabelframe1.place(x=20, y=40, height=355, width=540)
        self.TLabelframe1.configure(relief='')
        self.TLabelframe1.configure(text='''Editor Colours''')

        self.TLabel6 = ttk.Label(self.TLabelframe1)
        self.TLabel6.place(x=10, y=130, height=25, width=180
                , bordermode='ignore')
        self.TLabel6.configure(font="TkDefaultFont")
        self.TLabel6.configure(relief="flat")
        self.TLabel6.configure(anchor='e')
        self.TLabel6.configure(text='''Comment Colour:''')
        self.TLabel6.configure(compound='left')

        self.btnKeywordColour = ttk.Button(self.TLabelframe1)
        self.btnKeywordColour.place(x=366, y=50, height=25, width=28
                , bordermode='ignore')
        self.btnKeywordColour.configure(command=tkEditorDemo1_support.on_btnKeywordColour)
        self.btnKeywordColour.configure(text='''...''')
        self.btnKeywordColour.configure(compound='left')

        self.btnStringColour = ttk.Button(self.TLabelframe1)
        self.btnStringColour.place(x=370, y=90, height=25, width=28
                , bordermode='ignore')
        self.btnStringColour.configure(command=tkEditorDemo1_support.on_btnStringColour)
        self.btnStringColour.configure(text='''...''')
        self.btnStringColour.configure(compound='left')

        self.TLabel7 = ttk.Label(self.TLabelframe1)
        self.TLabel7.place(x=10, y=170, height=25, width=180
                , bordermode='ignore')
        self.TLabel7.configure(font="TkDefaultFont")
        self.TLabel7.configure(relief="flat")
        self.TLabel7.configure(anchor='e')
        self.TLabel7.configure(text='''Line Colour Background:''')
        self.TLabel7.configure(compound='left')

        self.TLabel13 = ttk.Label(self.TLabelframe1)
        self.TLabel13.place(x=10, y=210, height=23, width=180
                , bordermode='ignore')
        self.TLabel13.configure(font="TkDefaultFont")
        self.TLabel13.configure(relief="flat")
        self.TLabel13.configure(anchor='e')
        self.TLabel13.configure(text='''Editor Background color:''')
        self.TLabel13.configure(compound='left')

        self.btnCommentColour = ttk.Button(self.TLabelframe1)
        self.btnCommentColour.place(x=366, y=130, height=25, width=28
                , bordermode='ignore')
        self.btnCommentColour.configure(command=tkEditorDemo1_support.on_btnCommentColour)
        self.btnCommentColour.configure(text='''...''')
        self.btnCommentColour.configure(compound='left')

        self.btnCurrentLineColour = ttk.Button(self.TLabelframe1)
        self.btnCurrentLineColour.place(x=366, y=170, height=25, width=28
                , bordermode='ignore')
        self.btnCurrentLineColour.configure(command=tkEditorDemo1_support.on_btnCurrentLineColour)
        self.btnCurrentLineColour.configure(text='''...''')
        self.btnCurrentLineColour.configure(compound='left')

        self.btnEditorBgColour = ttk.Button(self.TLabelframe1)
        self.btnEditorBgColour.place(x=366, y=210, height=25, width=28
                , bordermode='ignore')
        self.btnEditorBgColour.configure(command=tkEditorDemo1_support.on_btnEditorBGColour)
        self.btnEditorBgColour.configure(text='''...''')
        self.btnEditorBgColour.configure(compound='left')

        self.TLabel5 = ttk.Label(self.TLabelframe1)
        self.TLabel5.place(x=10, y=90, height=25, width=180, bordermode='ignore')

        self.TLabel5.configure(font="TkDefaultFont")
        self.TLabel5.configure(relief="flat")
        self.TLabel5.configure(anchor='e')
        self.TLabel5.configure(text='''String Colour:''')
        self.TLabel5.configure(compound='left')

        self.TLabel4 = ttk.Label(self.TLabelframe1)
        self.TLabel4.place(x=10, y=50, height=25, width=180, bordermode='ignore')

        self.TLabel4.configure(font="TkDefaultFont")
        self.TLabel4.configure(relief="flat")
        self.TLabel4.configure(anchor='e')
        self.TLabel4.configure(text='''Keyword Colour:''')
        self.TLabel4.configure(compound='left')

        self.TEntry1 = ttk.Entry(self.TLabelframe1)
        self.TEntry1.place(x=196, y=50, height=25, width=166
                , bordermode='ignore')
        self.TEntry1.configure(exportselection="0")
        self.TEntry1.configure(textvariable=self.kwdColorData)
        self.TEntry1.configure(cursor="xterm")

        self.TEntry2 = ttk.Entry(self.TLabelframe1)
        self.TEntry2.place(x=196, y=90, height=25, width=166
                , bordermode='ignore')
        self.TEntry2.configure(exportselection="0")
        self.TEntry2.configure(textvariable=self.stringColorData)
        self.TEntry2.configure(cursor="xterm")

        self.tlblStringColor = ttk.Label(self.TLabelframe1)
        self.tlblStringColor.place(x=400, y=90, height=25, width=90
                , bordermode='ignore')
        self.tlblStringColor.configure(font="TkDefaultFont")
        self.tlblStringColor.configure(relief="sunken")
        self.tlblStringColor.configure(anchor='center')
        self.tlblStringColor.configure(textvariable=self.stringLabelTest)
        self.tlblStringColor.configure(compound='left')

        self.tlblKeywordColor = ttk.Label(self.TLabelframe1)
        self.tlblKeywordColor.place(x=400, y=50, height=25, width=90
                , bordermode='ignore')
        self.tlblKeywordColor.configure(font="TkDefaultFont")
        self.tlblKeywordColor.configure(relief="sunken")
        self.tlblKeywordColor.configure(anchor='center')
        self.tlblKeywordColor.configure(textvariable=self.KwdLabelTest)
        self.tlblKeywordColor.configure(compound='left')

        self.TEntry3 = ttk.Entry(self.TLabelframe1)
        self.TEntry3.place(x=196, y=130, height=25, width=166
                , bordermode='ignore')
        self.TEntry3.configure(exportselection="0")
        self.TEntry3.configure(textvariable=self.commentColourData)
        self.TEntry3.configure(cursor="xterm")

        self.TLblCommentColour = ttk.Label(self.TLabelframe1)
        self.TLblCommentColour.place(x=400, y=130, height=25, width=90
                , bordermode='ignore')
        self.TLblCommentColour.configure(font="TkDefaultFont")
        self.TLblCommentColour.configure(relief="sunken")
        self.TLblCommentColour.configure(anchor='center')
        self.TLblCommentColour.configure(textvariable=self.CommentLabelTest)
        self.TLblCommentColour.configure(compound='left')

        self.TEntry4 = ttk.Entry(self.TLabelframe1)
        self.TEntry4.place(x=196, y=170, height=25, width=166
                , bordermode='ignore')
        self.TEntry4.configure(exportselection="0")
        self.TEntry4.configure(textvariable=self.LineBgColorData)
        self.TEntry4.configure(cursor="xterm")

        self.TlblClineBackground = ttk.Label(self.TLabelframe1)
        self.TlblClineBackground.place(x=400, y=170, height=25, width=90
                , bordermode='ignore')
        self.TlblClineBackground.configure(font="TkDefaultFont")
        self.TlblClineBackground.configure(relief="sunken")
        self.TlblClineBackground.configure(anchor='center')
        self.TlblClineBackground.configure(textvariable=self.LineColorLabelTest)
        self.TlblClineBackground.configure(compound='left')

        self.TEntry6 = ttk.Entry(self.TLabelframe1)
        self.TEntry6.place(x=196, y=210, height=25, width=166
                , bordermode='ignore')
        self.TEntry6.configure(exportselection="0")
        self.TEntry6.configure(textvariable=self.EditorBgColorData)
        self.TEntry6.configure(cursor="xterm")

        self.TlblEditorBgColor = ttk.Label(self.TLabelframe1)
        self.TlblEditorBgColor.place(x=400, y=210, height=23, width=90
                , bordermode='ignore')
        self.TlblEditorBgColor.configure(font="TkDefaultFont")
        self.TlblEditorBgColor.configure(relief="sunken")
        self.TlblEditorBgColor.configure(anchor='center')
        self.TlblEditorBgColor.configure(textvariable=self.EditorLabelColorTest)
        self.TlblEditorBgColor.configure(compound='left')

        self.TLabelframe2 = ttk.Labelframe(self.framePrefs)
        self.TLabelframe2.place(x=562, y=40, height=145, width=320)
        self.TLabelframe2.configure(relief='')
        self.TLabelframe2.configure(text='''Indent''')

        self.TLabel12 = ttk.Label(self.TLabelframe2)
        self.TLabel12.place(x=20, y=50, height=23, width=100
                , bordermode='ignore')
        self.TLabel12.configure(font="TkDefaultFont")
        self.TLabel12.configure(relief="flat")
        self.TLabel12.configure(anchor='e')
        self.TLabel12.configure(text='''Indent Spaces:''')
        self.TLabel12.configure(compound='left')

        self.TEntry5 = ttk.Entry(self.TLabelframe2)
        self.TEntry5.place(x=120, y=50, height=25, width=166
                , bordermode='ignore')
        self.TEntry5.configure(exportselection="0")
        self.TEntry5.configure(textvariable=self.IndentData)
        self.TEntry5.configure(cursor="xterm")

    def popup0(self, event, *args, **kwargs):
        self.Popupmenu1 = tk.Menu(self.top, activebackground='beige'
                ,activeforeground='black', background='#a2a2a2'
                ,disabledforeground='#797979', foreground='black', tearoff=0)
        self.Popupmenu1.add_command(command=lambda :tkEditorDemo1_support.on_popCopy(args)
                ,compound='left', font="TkMenuFont", label='Copy')
        self.Popupmenu1.add_command(command=lambda :tkEditorDemo1_support.on_popCut(args)
                ,compound='left', font="TkMenuFont", label='Cut')
        self.Popupmenu1.add_command(compound='left', font="TkMenuFont"
                ,label='Paste')
        self.Popupmenu1.post(event.x_root, event.y_root)

from time import time, localtime, strftime
class ToolTip(tk.Toplevel):
    """ Provides a ToolTip widget for Tkinter. """
    def __init__(self, wdgt, msg=None, msgFunc=None, delay=0.5,
                 follow=True):
        self.wdgt = wdgt
        self.parent = self.wdgt.master
        tk.Toplevel.__init__(self, self.parent, bg='black', padx=1, pady=1)
        self.withdraw()
        self.overrideredirect(True)
        self.msgVar = tk.StringVar()
        if msg is None:
            self.msgVar.set('No message provided')
        else:
            self.msgVar.set(msg)
        self.msgFunc = msgFunc
        self.delay = delay
        self.follow = follow
        self.visible = 0
        self.lastMotion = 0
        self.msg = tk.Message(self, textvariable=self.msgVar, bg=_bgcolor,
                   fg=_fgcolor, font="TkTooltipFont",
                   aspect=1000)
        self.msg.grid()
        self.wdgt.bind('<Enter>', self.spawn, '+')
        self.wdgt.bind('<Leave>', self.hide, '+')
        self.wdgt.bind('<Motion>', self.move, '+')
    def spawn(self, event=None):
        self.visible = 1
        self.after(int(self.delay * 1000), self.show)
    def show(self):
        if self.visible == 1 and time() - self.lastMotion > self.delay:
            self.visible = 2
        if self.visible == 2:
            self.deiconify()
    def move(self, event):
        self.lastMotion = time()
        if self.follow is False:
            self.withdraw()
            self.visible = 1
        self.geometry('+%i+%i' % (event.x_root + 20, event.y_root - 10))
        try:
            self.msgVar.set(self.msgFunc())
        except:
            pass
        self.after(int(self.delay * 1000), self.show)
    def hide(self, event=None):
        self.visible = 0
        self.withdraw()
    def update(self, msg):
        self.msgVar.set(msg)
    def configure(self, **kwargs):
        backgroundset = False
        foregroundset = False
        # Get the current tooltip text just in case the user doesn't provide any.
        current_text = self.msgVar.get()
        # to clear the tooltip text, use the .update method
        if 'debug' in kwargs.keys():
            debug = kwargs.pop('debug', False)
            if debug:
                for key, value in kwargs.items():
                    print(f'key: {key} - value: {value}')
        if 'background' in kwargs.keys():
            background = kwargs.pop('background')
            backgroundset = True
        if 'bg' in kwargs.keys():
            background = kwargs.pop('bg')
            backgroundset = True
        if 'foreground' in kwargs.keys():
            foreground = kwargs.pop('foreground')
            foregroundset = True
        if 'fg' in kwargs.keys():
            foreground = kwargs.pop('fg')
            foregroundset = True

        fontd = kwargs.pop('font', None)
        if 'text' in kwargs.keys():
            text = kwargs.pop('text')
            if (text == '') or (text == "\n"):
                text = current_text
            else:
                self.msgVar.set(text)
        reliefd = kwargs.pop('relief', 'flat')
        justifyd = kwargs.pop('justify', 'left')
        padxd = kwargs.pop('padx', 1)
        padyd = kwargs.pop('pady', 1)
        borderwidthd = kwargs.pop('borderwidth', 2)
        wid = self.msg      # The message widget which is the actual tooltip
        if backgroundset:
            wid.config(bg=background)
        if foregroundset:
            wid.config(fg=foreground)
        wid.config(font=fontd)
        wid.config(borderwidth=borderwidthd)
        wid.config(relief=reliefd)
        wid.config(justify=justifyd)
        wid.config(padx=padxd)
        wid.config(pady=padyd)
#                   End of Class ToolTip

# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''
    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))
        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')
        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)
        # Copy geometry methods of master  (taken from ScrolledText.py)
        methods = tk.Pack.__dict__.keys() | tk.Grid.__dict__.keys() \
                  | tk.Place.__dict__.keys()
        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        container.bind('<Enter>', lambda e: _bound_to_mousewheel(e, container))
        container.bind('<Leave>', lambda e: _unbound_to_mousewheel(e, container))
        return func(cls, container, **kw)
    return wrapped

class ScrolledText(AutoScroll, tk.Text):
    '''A standard Tkinter Text widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        tk.Text.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)

import platform
def _bound_to_mousewheel(event, widget):
    child = widget.winfo_children()[0]
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        child.bind_all('<MouseWheel>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-MouseWheel>', lambda e: _on_shiftmouse(e, child))
    else:
        child.bind_all('<Button-4>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Button-5>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-Button-4>', lambda e: _on_shiftmouse(e, child))
        child.bind_all('<Shift-Button-5>', lambda e: _on_shiftmouse(e, child))

def _unbound_to_mousewheel(event, widget):
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        widget.unbind_all('<MouseWheel>')
        widget.unbind_all('<Shift-MouseWheel>')
    else:
        widget.unbind_all('<Button-4>')
        widget.unbind_all('<Button-5>')
        widget.unbind_all('<Shift-Button-4>')
        widget.unbind_all('<Shift-Button-5>')

def _on_mousewheel(event, widget):
    if platform.system() == 'Windows':
        widget.yview_scroll(-1*int(event.delta/120),'units')
    elif platform.system() == 'Darwin':
        widget.yview_scroll(-1*int(event.delta),'units')
    else:
        if event.num == 4:
            widget.yview_scroll(-1, 'units')
        elif event.num == 5:
            widget.yview_scroll(1, 'units')

def _on_shiftmouse(event, widget):
    if platform.system() == 'Windows':
        widget.xview_scroll(-1*int(event.delta/120), 'units')
    elif platform.system() == 'Darwin':
        widget.xview_scroll(-1*int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.xview_scroll(-1, 'units')
        elif event.num == 5:
            widget.xview_scroll(1, 'units')
def start_up():
    tkEditorDemo1_support.main()

if __name__ == '__main__':
    tkEditorDemo1_support.main()




