#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# ===============================================================
#                     tkEditorDemo1_support.py
# ---------------------------------------------------------------
# Written for users PAGE of Tkinter
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Author: Greg Walters
# Date Created: 2025-10-04 03:20:49
# Version 0.1.4
#
# ---------------------------------------------------------------
# Copyright © 2025 by G.D. Walters and Designated Geek Software
# ===============================================================
# Purpose:
#    Demonstration program for the tkEditor Metawidget
#
# ===============================================================
# Last Updated: 2025-10-07 03:23:29
# ---------------------------------------------------------------
#  0.1.1 - Initial coding
#  0.1.2 - Support for colour changes
#  0.1.3 - Added icon
#        - Started popup Copy, cut and paste - NOT FULLY TESTED!
#  0.1.4 - Started add tab and editor
#        -

# Support module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Oct 03, 2025 08:01:29 AM CDT  platform: Linux
#    Oct 03, 2025 09:02:50 AM CDT  platform: Linux
#    Oct 03, 2025 09:05:36 AM CDT  platform: Linux
#    Oct 03, 2025 10:37:16 AM CDT  platform: Linux
#    Oct 05, 2025 06:17:41 AM CDT  platform: Linux
#    Oct 05, 2025 06:19:51 AM CDT  platform: Linux
#    Oct 05, 2025 07:44:25 AM CDT  platform: Linux
#    Oct 05, 2025 10:48:01 AM CDT  platform: Linux
#    Oct 05, 2025 03:36:00 PM CDT  platform: Linux
#    Oct 07, 2025 03:29:11 AM CDT  platform: Linux

import sys
import os
import datetime
import toml

# Import the tkEditor Metawidget

import tkEditor1

import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
from tkinter import font
import tkinter.messagebox as messagebox
from tkinter import simpledialog
from tkinter import colorchooser
from tkinter.filedialog import (
    askdirectory,
    askopenfilename,
    asksaveasfile,
    asksaveasfilename,
)
from tkinter.simpledialog import askfloat, askinteger, askstring

import tkEditorDemo1

_debug = False  # False to eliminate debug printing from callback functions.
location = tkEditorDemo1._location
programName = "tkEditor Demo #1"
version = "0.1.4"


def main(*args):
    """Main entry point for the application."""
    global root
    root = tk.Tk()
    root.protocol("WM_DELETE_WINDOW", root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = tkEditorDemo1.Toplevel1(_top1)
    startup()
    root.mainloop()


def startup():
    global config
    global cur_keyword_color, cur_string_color, cur_comment_color, cur_current_line_bg_color, cur_editor_bg_color, colorSet
    # "Hide" About and Prefs frames
    _w1.frameAbout.lower()
    _w1.framePrefs.lower()
    read_config()
    setup_colorSet()
    # Set a global instance of the editor.
    global ed1, ed2

    # instantiate the editor object into Tab0 frameEd1 and Tab1 (frameEd2)
    ed1 = tkEditor1.CodeEditor(_w1.frameEd1, indent_width=4)
    print(f"{type(ed1)}")
    ed2 = tkEditor1.CodeEditor(_w1.frameEd2)
    # Set the title of the Toplevel
    _top1.title(f"{programName} - {version}")

    # Apply the colourSet to the editors
    ed1._update_editor_colours(colorSet)
    ed2._update_editor_colours(colorSet)
    # Get the version of the editor code and the licence
    libVer = ed1.get_version()
    libLic = ed1.get_licence()
    if _debug:
        print(f"{libVer=}")
        print(f"{libLic=}")
    _w1.StatusInfo1.set(f"tkEditor1 Version {libVer}")
    _w1.StatusInfo2.set(f"License: {libLic}")
    # Housekeeping on the TNotebook
    global current_filename
    current_filename = ""
    _w1.TNotebook1.tab(0, text="Unknown")
    # _w1.TNotebook1.tab(1, state="hidden")
    _w1.TNotebook1.tab(1, text="Unknown")
    _w1.TNotebook1.bind("<<NotebookTabChanged>>", on_NotebookTabChange)
    global totalTabs
    totalTabs = len(_w1.TNotebook1.tabs())
    if _debug:
        print(f"{totalTabs=}")
    global currenttab
    currenttab = _w1.TNotebook1.index("current")
    if _debug:
        print(f"{currenttab=}")

    # Load up the defaults into the prefs Frame.
    setupPrefFrame()

    # Load the About frame
    setupAboutFrame()

    # Status bar Time code...
    global timer_id
    timer_id = root.after(0, on_time_update)
    set_icon()

    # Disable the 'Add Tab' button for now.
    _w1.btnAddTab.configure(state=DISABLED)


# ==============================
#    End of function startup
# ==============================


def setup_colorSet():
    global config
    global cur_keyword_color, cur_string_color, cur_comment_color, cur_current_line_bg_color, cur_editor_bg_color, colorSet, indent
    cur_keyword_color = config["editor"]["keyword_color"]
    cur_string_color = config["editor"]["string_color"]
    cur_comment_color = config["editor"]["comment_color"]
    cur_current_line_bg_color = config["editor"]["current_line_bg_color"]
    cur_editor_bg_color = config["editor"]["editor_bg_color"]
    indent = config["editor"]["indent"]
    colorSet = {}
    colorSet = {
        "keywordColor": cur_keyword_color,
        "stringColor": cur_string_color,
        "commentColor": cur_comment_color,
        "lineBgColor": cur_current_line_bg_color,
        "editorBgColor": cur_editor_bg_color,
    }


def setupAboutFrame():
    # Load up the ScrolledTextbox info in the About Frame
    about_info = """ Welcome to the tkEditor demo program.
    
    Demo version - 0.1.3
    tkEditor1 version - 0.1.3

    The tkEditor is a Tkinter Metawidget was created by ChatGPT 5.0 from a concept by Greg Walters.  This code was then turned into a Tkinter library which can be easily imported into most any Python/Tkinter program, but was originally created to be used in a PAGE GUI Designer program.

    The goal of this project was to create a BASIC text editor that has synced line numbers that requires ABSOLUTELY NO external libraries.  So far the tkEditor1 Metawidget keeps this requirement.  The demo program, currently DOES require at least one external library (for writing the TOML configuration file). Another goal of this project was to provide a usable Metawidget that other PAGE (and Tkinter) programmers can use for education on creation and use of Metawidgets.

    SOME of the features of the tkEditor Metawidget are:
        * Auto-indent which is configurable by the user (for new text files)
        * Line numbers that scroll with the text.
        * Basic Python syntax highlighting (user configurable)
        * VERY BASIC code folding.
        * Fairly light weight in memory usage.  On my machine, the program uses 14.6 MB at startup.  
             Depending on the size of the files loaded, each file adds about 1 additional Mb.
        
          

    Here is a list of some of the working things that the tkEditorDemo1 program does as of release version 0.1.3
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

        *  Currently starts up with two editor windows.
        *  Colour assignment works        
        *  Supports a configuration file.  Currently only saves colour assignments and indent size.  
        *  Indent currently defaults to 4 spaces.
        *  The following 'normal' editiing keyboard shortcuts work...
              * <Ctrl> C    - Copy
              * <Ctrl> X    - Cuts (deletes)
              * <Ctrl> V    - Paste
              * <Ctrl> Z    - Undo
              * <Ctrl> f    - Toggle fold of current block (Python files only)
              * <Alt> Left  - Fold current block (Python files only)
              * <Alt> Right - Unfolds current block (Python files only)

    

    Known Limitations...
      At this time (6 October 2025), the biggest limitation is in the code folding routines and that the code highlighting only works for Python .py files.  Hopefully I can eventually expand this to the possibility of support of .md and .rst (Markdown and Restructured Text) files as well.  But this is in the far future at this point.

      One other limitation is that there is not support to convert Tabs to spaces and that changing the indent amount only works on new files.  Loading an existing file into the editor will NOT apply ANY different indentations.  This is to preserve the format of the existing file.
      

    Still to do 
    ----------------------

    A few things are currently on my mental list of things to do.  However, I will try to enumerate them here.

        * Configuration file for the program. (Uses TOML)
        * Link the preferences to the library.
        * EVENTUALLY support formatting tags (bold, italic, etc.) for the tk.ScrolledText widget in the About file.  (This file.)
        * Clean up the code in both the tkEditor and demo files.
        * Add ability to have more editors in tabs of the TNotebook.
        * Add AT LEAST popup menus for tkEditor supporting Copy, Cut, Paste
        *
        *
        *

    For more information, please see the help document (currently unavaiable since it's creation is in process).
    """

    _w1.stAbout.insert(1.0, about_info)


def on_time_update():
    # ======================================================
    # Callback function for the Time display
    # ======================================================
    global timer_id
    nowstring = f"{datetime.datetime.now():%X}"
    _w1.StatusTime.set(nowstring)
    timer_id = root.after(500, on_time_update)


def setupPrefFrame():
    # Clear all the TEdit widgets on the Prefs Frame...
    _w1.kwdColorData.set("")
    _w1.stringColorData.set("")
    _w1.commentColourData.set("")
    _w1.LineBgColorData.set("")
    _w1.EditorBgColorData.set("")
    _w1.IndentData.set(4)
    global def_keyword_color, def_string_color, def_comment_color, def_current_line_bg_color, def_editor_bg_color
    global cur_keyword_color, cur_string_color, cur_comment_color, cur_current_line_bg_color, cur_editor_bg_color
    bgcolor = "white"
    def_editor_bg_color = "white"
    def_keyword_color = "#0000ff"
    def_string_color = "#a31515"
    def_comment_color = "#008000"
    def_current_line_bg_color = "#f0f8ff"
    def_current_Editor_bg_color = "white"
    #
    _w1.tlblKeywordColor.configure(background=bgcolor, foreground=cur_keyword_color)
    _w1.tlblStringColor.configure(background=bgcolor, foreground=cur_string_color)
    _w1.TLblCommentColour.configure(background=bgcolor, foreground=cur_comment_color)
    _w1.TlblClineBackground.configure(
        background=cur_current_line_bg_color, foreground="black"
    )
    _w1.TlblEditorBgColor.configure(
        background=cur_editor_bg_color, foreground=def_string_color
    )
    _w1.KwdLabelTest.set("Test Text")
    _w1.stringLabelTest.set("Test Text")
    _w1.CommentLabelTest.set("Test Text")
    _w1.LineColorLabelTest.set("Test Text")
    _w1.EditorLabelColorTest.set("Test Text")

    _w1.kwdColorData.set(cur_keyword_color)
    _w1.stringColorData.set(cur_string_color)
    _w1.commentColourData.set(cur_comment_color)
    _w1.LineBgColorData.set(cur_current_line_bg_color)
    _w1.EditorBgColorData.set(cur_editor_bg_color)
    colorSet = {}
    colorSet = {
        "keywordColor": cur_keyword_color,
        "stringColor": cur_string_color,
        "commentColor": cur_comment_color,
        "lineBgColor": cur_current_line_bg_color,
        "editorBgColor": cur_editor_bg_color,
    }

    ed1._update_editor_colours(colorSet)


def on_NotebookTabChange(*args):
    # Callback function for TNotebook
    global currenttab
    currenttab = _w1.TNotebook1.index("current")
    print(f"{currenttab=}")
    if _debug:
        print(f"{currenttab=}")


def on_btnClear(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnClear")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    if currenttab == 0:
        editorToUse = ed1
    elif currenttab == 1:
        editorToUse = ed2
    elif currenttab == 2:
        editorToUse = ed3
    elif currenttab == 3:
        editorToUse = ed4
    elif currenttab == 4:
        editorToUse = ed5
    elif currenttab == 5:
        editorToUse = ed6
    editorToUse.clear_editor()


def on_btnExit(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnExit")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    sys.exit()


def on_btnFileNew(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnFileNew")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    global current_filename
    current_filename = ""
    _w1.TNotebook1.tab(currenttab, text="Unknown")
    on_btnClear()


def on_btnFileOpen(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnFileOpen")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    #

    global ed1, ed2, ed3, ed4, ed5, ed6, current_filename, basefile, currenttab, editorToUse

    if currenttab == 0:
        editorToUse = ed1
    elif currenttab == 1:
        editorToUse = ed2
    elif currenttab == 2:
        editorToUse = ed3
    elif currenttab == 3:
        editorToUse = ed4
    elif currenttab == 4:
        editorToUse = ed5
    elif currenttab == 5:
        editorToUse = ed6

    basefile = ""
    if _debug:
        print("pyed2a_support.on_btnFileOpen")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    filename = askopenfilename(
        initialdir=location,
        title="Select A File",
        parent=_top1,
        filetypes=(
            ("Python files", "*.py"),
            ("All Files", "*.*"),
            ("ttd files", "*.ttd"),
            ("Markdown", "*.md"),
            ("RST files", "*.rst"),
            ("text files", "*.txt"),
        ),
    )
    # print(filename)
    if filename != ():
        if filename != "":
            if _debug:
                print(f"{filename}")
            # return filename
            editorToUse.clear_editor()
            editorToUse.load_file(filename)
            current_filename = filename
            basefile = os.path.basename(current_filename)
    _top1.title(f"{programName} - {version}")
    # if _debug:
    print(f"{basefile=} - {editorToUse=}")
    _w1.TNotebook1.tab(currenttab, text=basefile)


def on_btnFileSave(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnFileSave")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    global current_filename, basefile

    if currenttab == 0:
        editorToUse = ed1
    elif currenttab == 1:
        editorToUse = ed2
    contents = editorToUse.text.get(1.0, END)
    if current_filename == "":
        # ask filename and location
        file_path = asksaveasfilename(
            defaultextension=".txt",
            filetypes=[
                ("Python files", "*.py"),
                ("ttd files", "*.ttd"),
                ("Markdown", "*.md"),
                ("RST files", "*.rst"),
                ("text files", "*.txt"),
                ("All Files", "*.*"),
            ],
            initialdir=location,  # Optional: set initial directory
            title="Save your file",  # Optional: set dialog title
        )
        if file_path:
            # User selected a file path, now you can write data to it
            with open(file_path, "w") as f:
                f.write(contents)
            if _debug:
                print(f"File saved to: {file_path}")
            basefile = os.path.basename(file_path)
            _top1.title(f"{programName} - {version} - {basefile} - Saved")
            _w1.TNotebook1.tab(currenttab, text=basefile)

        else:
            print("Save operation cancelled.")
    else:
        with open(current_filename, "w") as f:
            f.write(contents)
        if _debug:
            print(f"File Write complete")
    _top1.title(f"{programName} - {version} - Saved")
    _w1.TNotebook1.tab(currenttab, text=basefile)


def write_file(filename, strng):
    with open(filename, "w") as f:
        f.write(strng)


def read_file(filename):
    # ======================================================
    # function read_file()
    # ======================================================
    # Read file, leaving end of lines
    # ======================================================
    with open(filename) as f:
        lines = f.read()
    return lines


def on_bthAbout(*args):
    if _debug:
        print("tkEditorDemo1_support.on_bthAbout")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    _w1.frameAbout.lift()


def on_btnHelp(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnHelp")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    titl = f"{programName}"
    msg = "Sorry, but the help fucntion is still under development."
    parent = _top1
    ico = messagebox.INFO
    messagebox.showinfo(titl, msg, parent=parent, icon=ico)


def on_btnAboutDismiss(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnAboutDismiss")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    _w1.frameAbout.lower()


def on_btnFileSaveAs(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnFileSaveAs")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    if currenttab == 0:
        editorToUse = ed1
    elif currenttab == 1:
        editorToUse = ed2
    current_filename = ""
    contents = editorToUse.text.get(1.0, END)
    if current_filename == "":
        # ask filename and location
        file_path = asksaveasfilename(
            defaultextension=".txt",
            filetypes=[
                ("Python files", "*.py"),
                ("All Files", "*.*"),
                ("ttd files", "*.ttd"),
                ("Markdown", "*.md"),
                ("RST files", "*.rst"),
                ("text files", "*.txt"),
            ],
            initialdir=location,  # Optional: set initial directory
            title="Save your file",  # Optional: set dialog title
        )
        if file_path:
            # User selected a file path, now you can write data to it
            with open(file_path, "w") as f:
                f.write(contents)
            if _debug:
                print(f"File saved to: {file_path}")
            basefile = os.path.basename(file_path)
            _top1.title(f"{programName} - {version} - {basefile} - Saved")
            _w1.TNotebook1.tab(currenttab, text=basefile)
        else:
            if _debug:
                print("Save operation cancelled.")
    else:
        with open(current_filename, "w") as f:
            f.write(contents)
        if _debug:
            print(f"File Write complete")
        basefile = os.path.basename(current_filename)
        _top1.title(f"{programName} - {version} - {basefile} - Saved")
        _w1.TNotebook1.tab(currenttab, text=basefile)


# ==============================
#    Colour set code
# ==============================
def on_btnKeywordColour(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnKeywordColour")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()

    global def_keyword_color, def_string_color, def_comment_color, def_current_line_bg_color, def_editor_bg_color
    global cur_keyword_color, cur_string_color, cur_comment_color, cur_current_line_bg_color, cur_editor_bg_color
    choice = colorchooser.askcolor(def_keyword_color)
    if _debug:
        print(f"{choice[1]=}")
    _w1.kwdColorData.set(choice[1])
    _w1.tlblKeywordColor.configure(foreground=choice[1])
    cur_keyword_color = choice[1]
    # Write to globals and config.toml


def on_btnStringColour(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnStringColour")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    global def_keyword_color, def_string_color, def_comment_color, def_current_line_bg_color, def_editor_bg_color
    global cur_keyword_color, cur_string_color, cur_comment_color, cur_current_line_bg_color, cur_editor_bg_color
    choice = colorchooser.askcolor(def_string_color)
    if _debug:
        print(f"{choice=}")
    _w1.stringColorData.set(choice[1])
    _w1.tlblStringColor.configure(foreground=choice[1])
    cur_string_color = choice[1]
    # Write to globals and config.toml


def on_btnCommentColour(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnCommentColour")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    global def_keyword_color, def_string_color, def_comment_color, def_current_line_bg_color, def_editor_bg_color
    global cur_keyword_color, cur_string_color, cur_comment_color, cur_current_line_bg_color, cur_editor_bg_color
    choice = colorchooser.askcolor(def_comment_color)
    if _debug:
        print(f"{choice=}")

    _w1.commentColourData.set(choice[1])
    _w1.TLblCommentColour.configure(foreground=choice[1])
    cur_comment_color = choice[1]
    # Write to globals and config.toml


def on_btnCurrentLineColour(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnCurrentLineColour")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    global def_keyword_color, def_string_color, def_comment_color, def_current_line_bg_color, def_editor_bg_color
    global cur_keyword_color, cur_string_color, cur_comment_color, cur_current_line_bg_color, cur_editor_bg_color
    choice = colorchooser.askcolor(def_current_line_bg_color)
    if _debug:
        print(f"{choice=}")
    _w1.LineBgColorData.set(choice[1])
    _w1.TlblClineBackground.configure(background=choice[1])
    cur_current_line_bg_color = choice[1]
    # Write to globals and config.toml


def on_btnEditorBGColour(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnEditorBGColour")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()

    global def_keyword_color, def_string_color, def_comment_color, def_current_line_bg_color, def_editor_bg_color
    global cur_keyword_color, cur_string_color, cur_comment_color, cur_current_line_bg_color, cur_editor_bg_color
    choice = colorchooser.askcolor(def_editor_bg_color)
    if _debug:
        print(f"{choice[1]=}")
    _w1.EditorBgColorData.set(choice[1])
    _w1.TlblEditorBgColor.configure(background=choice[1], foreground="black")
    cur_editor_bg_color = choice[1]
    # Write to globals and config.toml


def on_btnPrefDismiss(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnPrefDismiss")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    _w1.framePrefs.lower()


def on_btnPrefsIgnoreChanges(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnPrefsIgnoreChanges")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()


# ==============================
#    Show the Prefs frame
# ==============================
def on_btnPrefs(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnPrefs")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    _w1.framePrefs.lift()


def on_btnPrefsSaveChanges(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnPrefsSaveChanges")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    # Create an enpty structure
    global cur_keyword_color, cur_string_color, cur_comment_color, cur_current_line_bg_color, cur_editor_bg_color, colorSet
    colorSet = {}
    colorSet = {
        "keywordColor": cur_keyword_color,
        "stringColor": cur_string_color,
        "commentColor": cur_comment_color,
        "lineBgColor": cur_current_line_bg_color,
        "editorBgColor": cur_editor_bg_color,
    }
    ed1._update_editor_colours(colorSet)
    ed2._update_editor_colours(colorSet)
    _w1.StatusInfo1.set(f"  Color set updated.")

    titl = f"{programName}"
    msg = "ColorSet has been updated"
    ico = messagebox.INFO
    messagebox.showinfo(titl, msg, parent=_top1, icon=ico)
    write_config()


# ==============================
#    Read and write config file
# ==============================
def read_config():
    global config
    global cur_keyword_color, cur_string_color, cur_comment_color, cur_current_line_bg_color, cur_editor_bg_color, colorSet
    with open("config.toml", "r") as f:
        config = toml.load(f)

    _w1.StatusInfo1.set(f"{config=}")


def write_config():
    global config
    global cur_keyword_color, cur_string_color, cur_comment_color, cur_current_line_bg_color, cur_editor_bg_color, colorSet
    if _debug:
        print(f" CurrentConfig:{config}")
    # config["editor"][colorSet] = colorSet
    config["editor"]["keyword_color"] = cur_keyword_color
    config["editor"]["string_color"] = cur_string_color
    config["editor"]["comment_color"] = cur_comment_color
    config["editor"]["current_line_bg_color"] = cur_current_line_bg_color
    config["editor"]["editor_bg_color"] = cur_editor_bg_color
    with open("config.toml", "w") as f:
        toml.dump(config, f)


def set_icon():
    # ======================================================
    # Sets the application icon...
    # ======================================================
    global progImagesPath
    img = os.path.join(location, "graphics", "accessories-text-editor.png")
    p1 = tk.PhotoImage(file=img)
    root.tk.call("wm", "iconphoto", root._w, p1)


def on_btnAddTab(*args):
    global totalTabs
    if _debug:
        print("tkEditorDemo1_support.on_btnAddTab")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()

    totalTabs = _w1.TNotebook1.index(END)
    currenttab = _w1.TNotebook1.index("current")
    print(f"{totalTabs=}")
    NewTabNumber = totalTabs
    NewTabName = f"TNotebook1_t{totalTabs}"
    NewTabName = tk.Frame(_w1.TNotebook1)
    displayName = f"NewEditorNumber{totalTabs+1}"
    _w1.TNotebook1.add(NewTabName, padding=3)
    _w1.TNotebook1.tab(
        NewTabNumber,
        text="New Tab Page",
        compound="left",
    )
    bg = tkEditorDemo1._bgcolor
    NewTabName.configure(background=bg)
    NewTabName.configure(highlightbackground=bg)
    NewFrameName = f"TFrame{NewTabNumber}"
    NewFrameName = ttk.Frame(NewTabName)
    NewFrameName.place(x=4, y=4, height=685, width=1102)
    NewFrameName.configure(relief="sunken")
    NewFrameName.configure(borderwidth="2")
    ttabs = totalTabs + 1
    # Create a new editor name
    newEditor = f"ed{ttabs}"
    print(f"New Editor Created...Name {newEditor}")
    newEditor = tkEditor1.CodeEditor(NewFrameName)
    newEditor._update_editor_colours(colorSet)
    print(f"{newEditor=} - {type(newEditor)}")
    totalTabs = _w1.TNotebook1.index(END)
    print(f"{currenttab=}")
    ct = _w1.TNotebook1.select(NewTabNumber)
    print(f"{ct=}")
    tt = len(_w1.TNotebook1.tabs())
    print(f"{tt=}")
    editorToUse = newEditor
    print(f"Current Editor = {newEditor}")


if __name__ == "__main__":
    tkEditorDemo1.start_up()
