#############################################################################
# Generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#  Oct 03, 2025 10:37:28 AM CDT  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
    computergeek_transback_175x247_png "./graphics/computergeek transback.175x247.png" 
    system_shutdown_png "./graphics/system-shutdown.png" 
    question_png "./graphics/question.png" 
    information_png "./graphics/information.png" 
    document_save_png "./graphics/document-save.png" 
    document_open_png "./graphics/document-open.png" 
    document_new_png "./graphics/document-new.png" 
    edit_clear_png "./graphics/edit-clear.png" 
    document_save_as_png "./graphics/document-save-as.png" 
}
vTcl:create_project_images $image_list   ;# In image.tcl

#######  Default Fonts ########
set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkTooltipFont
set vTcl(actual_gui_font_tooltip_name)  TkTooltipFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) Absolute
set vTcl(mode) Absolute
set vTcl(project_theme) notasdark



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base

############ toplevel.wgt #############################
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -borderwidth 0 -relief flat -background #a2a2a2 -container 0 \
        -height 0 -highlightbackground #a2a2a2 -highlightcolor black \
        -highlightthickness 0 -padx 0 -pady 0 -takefocus 0 -width 0 
    wm focusmodel $top passive
    wm geometry $top 1141x843+745+342
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 4465 1410
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    ttk::frame "$top.tFr52" \
        -borderwidth 2 -relief sunken -width 125 -height 75 -style "" 
    vTcl:DefineAlias "$top.tFr52" "frameStatus" vTcl:WidgetProc "Toplevel1" 1
    ttk::frame "$top.tFr51" \
        -borderwidth 2 -relief sunken -width 1130 -height 735 -style "" 
    vTcl:DefineAlias "$top.tFr51" "frameMain" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tFr51
    vTcl::widgets::ttk::notebook::createCmd "$site_3_0.tNo53" \
        -width 1114 -height 733 -takefocus ttk::takefocus -style "" 
    vTcl:DefineAlias "$site_3_0.tNo53" "TNotebook1" vTcl:WidgetProc "Toplevel1" 1
    frame "$site_3_0.tNo53.t0" \
        -borderwidth 0 -relief flat -background #a2a2a2 -container 0 \
        -height 0 -highlightbackground #a2a2a2 -highlightcolor black \
        -highlightthickness 0 -padx 0 -pady 0 -takefocus 0 -width 0 
    vTcl:DefineAlias "$site_3_0.tNo53.t0" "TNotebook1_t1" vTcl:WidgetProc "Toplevel1" 1
    $site_3_0.tNo53 add $site_3_0.tNo53.t0 \
        -padding 0 -sticky nsew -state normal -text "Page 1" -compound left \
        -underline -1 
    set site_5_0  $site_3_0.tNo53.t0
    ttk::frame "$site_5_0.tFr54" \
        -borderwidth 2 -relief sunken -width 1102 -height 685 -style "" 
    vTcl:DefineAlias "$site_5_0.tFr54" "frameEd1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_5_0.tFr54
# add p1 basename = $site_5_0.tFr54
    place $site_5_0.tFr54 \
        -in $site_5_0 -x 4 -y 4 -width 1102 -relwidth 0 -height 685 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame "$site_3_0.tNo53.t1" \
        -borderwidth 0 -relief flat -background #a2a2a2 -container 0 \
        -height 0 -highlightbackground #a2a2a2 -highlightcolor black \
        -highlightthickness 0 -padx 0 -pady 0 -takefocus 0 -width 0 
    vTcl:DefineAlias "$site_3_0.tNo53.t1" "TNotebook1_t2" vTcl:WidgetProc "Toplevel1" 1
    $site_3_0.tNo53 add $site_3_0.tNo53.t1 \
        -padding 0 -sticky nsew -state normal -text "Page 2" -compound left \
        -underline -1 
    set site_5_1  $site_3_0.tNo53.t1
    ttk::frame "$site_5_1.tFr55" \
        -borderwidth 2 -relief sunken -width 1102 -height 685 -style "" 
    vTcl:DefineAlias "$site_5_1.tFr55" "frameEd2" vTcl:WidgetProc "Toplevel1" 1
# add p1 basename = $site_5_1.tFr55
    place $site_5_1.tFr55 \
        -in $site_5_1 -x 4 -y 4 -width 1102 -relwidth 0 -height 685 \
        -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $site_3_0.tNo53
    place $site_3_0.tNo53 \
        -in $site_3_0 -x 6 -y 3 -width 1114 -relwidth 0 -height 733 \
        -relheight 0 -anchor nw -bordermode ignore 
    ttk::frame "$top.tFr56" \
        -borderwidth 2 -relief sunken -width 1115 -height 735 -cursor fleur \
        -style "" 
    vTcl:DefineAlias "$top.tFr56" "frameAbout" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tFr56
    ttk::label "$site_3_0.tLa58" \
        -font "TkDefaultFont" -relief flat -anchor center -justify left \
        -text "About tkEditorDemo1" -underline -1 -width 230 -compound left \
        -state normal -style "" 
    vTcl:DefineAlias "$site_3_0.tLa58" "TLabel2" vTcl:WidgetProc "Toplevel1" 1
    ttk::label "$site_3_0.tLa59" \
        -font "TkDefaultFont" -relief flat -anchor center -justify left \
        -text "Copyright © 2025, 2026 by Greg Walters and Designated Geek Software
" \
        -underline -1 -width 640 -compound left -state normal -style "" 
    vTcl:DefineAlias "$site_3_0.tLa59" "TLabel3" vTcl:WidgetProc "Toplevel1" 1
    ttk::label "$site_3_0.tLa57" \
        -font "TkDefaultFont" -relief flat -anchor w -justify left \
        -underline -1 -image computergeek_transback_175x247_png \
        -compound left -state normal -style "" 
    vTcl:DefineAlias "$site_3_0.tLa57" "TLabel1" vTcl:WidgetProc "Toplevel1" 1
    ttk::frame "$site_3_0.tFr60" \
        -borderwidth 2 -relief groove -width 725 -height 425 -style "" 
    vTcl:DefineAlias "$site_3_0.tFr60" "TFrame2" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.tFr60
    vTcl::widgets::ttk::scrolledtext::CreateCmd "$site_4_0.scr61" \
        -borderwidth 2 -relief groove -background #a2a2a2 -container 0 \
        -height 75 -highlightbackground #a2a2a2 -highlightcolor black \
        -highlightthickness 0 -padx 0 -pady 0 -takefocus 0 -width 125 
    vTcl:DefineAlias "$site_4_0.scr61" "stAbout" vTcl:WidgetProc "Toplevel1" 1

    $site_4_0.scr61.01 configure -background white \
        -exportselection 0 \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #a2a2a2 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #d9d9d9 \
        -selectforeground black \
        -width 10 \
        -wrap none
    vTcl:copy_lock $site_4_0.scr61
# add p1 basename = $site_4_0.scr61
    place $site_4_0.scr61 \
        -in $site_4_0 -x 1 -y 2 -width 722 -relwidth 0 -height 422 \
        -relheight 0 -anchor nw -bordermode ignore 
    ttk::button "$site_3_0.tBu51" \
        -command "on_btnAboutDismiss" -default normal \
        -takefocus ttk::takefocus -text "Dismiss" -underline -1 -width 148 \
        -compound left -state normal -style "bold.TButton" \
        -style bold.TButton 
    vTcl:DefineAlias "$site_3_0.tBu51" "btmAboutDismiss" vTcl:WidgetProc "Toplevel1" 1
# add p1 basename = $site_3_0.tLa58
    place $site_3_0.tLa58 \
        -in $site_3_0 -x 440 -y 40 -width 230 -relwidth 0 -height 53 \
        -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $site_3_0.tLa59
    place $site_3_0.tLa59 \
        -in $site_3_0 -x 240 -y 100 -width 640 -relwidth 0 -height 83 \
        -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $site_3_0.tLa57
    place $site_3_0.tLa57 \
        -in $site_3_0 -x 927 -y 270 -width 183 -relwidth 0 -height 251 \
        -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $site_3_0.tFr60
    place $site_3_0.tFr60 \
        -in $site_3_0 -x 197 -y 229 -width 725 -relwidth 0 -height 425 \
        -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $site_3_0.tBu51
    place $site_3_0.tBu51 \
        -in $site_3_0 -x 490 -y 680 -width 148 -relwidth 0 -height 39 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.tFr56
    ttk::frame "$top.tFr50" \
        -borderwidth 2 -relief sunken -width 125 -height 75 -style "" 
    vTcl:DefineAlias "$top.tFr50" "TFrame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tFr50
    ttk::button "$site_3_0.tBu51" \
        -command "on_btnExit" -default normal -takefocus ttk::takefocus \
        -underline -1 -image system_shutdown_png -compound left -state normal \
        -style "Toolbutton" -style Toolbutton 
    vTcl:DefineAlias "$site_3_0.tBu51" "btnExit" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tBu51 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Exit}
    }
    vTcl:copy_lock $site_3_0.tBu51
    ttk::button "$site_3_0.tBu50" \
        -command "on_btnHelp" -default normal -takefocus ttk::takefocus \
        -underline -1 -image question_png -compound left -state normal \
        -style "" 
    vTcl:DefineAlias "$site_3_0.tBu50" "btnHelp" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tBu50 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Help}
    }
    vTcl:copy_lock $site_3_0.tBu50
    ttk::button "$site_3_0.tBu49" \
        -command "on_bthAbout" -default normal -takefocus ttk::takefocus \
        -underline -1 -image information_png -compound left -state normal \
        -style "" 
    vTcl:DefineAlias "$site_3_0.tBu49" "btnAbout" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tBu49 <<SetBalloon>> {
        set ::vTcl::balloon::%W {About the program}
    }
    vTcl:copy_lock $site_3_0.tBu49
    ttk::button "$site_3_0.tBu55" \
        -command "on_btnFileSave" -default normal -takefocus ttk::takefocus \
        -underline -1 -image document_save_png -compound left -state normal \
        -style "" 
    vTcl:DefineAlias "$site_3_0.tBu55" "btnFileSave" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tBu55 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Save the current file}
    }
    vTcl:copy_lock $site_3_0.tBu55
    ttk::button "$site_3_0.tBu52" \
        -command "on_btnFileOpen" -default normal -takefocus ttk::takefocus \
        -underline -1 -image document_open_png -compound left -state normal \
        -style "" 
    vTcl:DefineAlias "$site_3_0.tBu52" "btnFileOpen" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tBu52 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Open File}
    }
    ttk::button "$site_3_0.tBu54" \
        -command "on_btnFileNew" -default normal -takefocus ttk::takefocus \
        -underline -1 -image document_new_png -compound left -state normal \
        -style "" 
    vTcl:DefineAlias "$site_3_0.tBu54" "btnFileNew" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tBu54 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Create a NEW file}
    }
    vTcl:copy_lock $site_3_0.tBu54
    ttk::button "$site_3_0.tBu53" \
        -command "on_btnClear" -default normal -takefocus ttk::takefocus \
        -underline -1 -image edit_clear_png -compound left -state normal \
        -style "" 
    vTcl:DefineAlias "$site_3_0.tBu53" "btnClear" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tBu53 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Clear the Editor}
    }
    ttk::button "$site_3_0.tBu56" \
        -command "on_btnFileSaveAs" -default normal -underline -1 \
        -image document_save_as_png -compound left -state normal -style "" 
    vTcl:DefineAlias "$site_3_0.tBu56" "btnFileSaveAs" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tBu56 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Save Current File As....}
    }
    vTcl:copy_lock $site_3_0.tBu56
# add p1 basename = $site_3_0.tBu51
    place $site_3_0.tBu51 \
        -in $site_3_0 -x 1081 -y 2 -width 42 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $site_3_0.tBu50
    place $site_3_0.tBu50 \
        -in $site_3_0 -x 1026 -y 3 -width 42 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $site_3_0.tBu49
    place $site_3_0.tBu49 \
        -in $site_3_0 -x 982 -y 3 -width 42 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $site_3_0.tBu55
    place $site_3_0.tBu55 \
        -in $site_3_0 -x 106 -y 3 -width 42 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $site_3_0.tBu52
    place $site_3_0.tBu52 \
        -in $site_3_0 -x 58 -y 3 -width 42 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $site_3_0.tBu54
    place $site_3_0.tBu54 \
        -in $site_3_0 -x 10 -y 3 -width 42 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $site_3_0.tBu53
    place $site_3_0.tBu53 \
        -in $site_3_0 -x 200 -y 3 -width 42 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $site_3_0.tBu56
    place $site_3_0.tBu56 \
        -in $site_3_0 -x 153 -y 3 -width 42 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
# add p1 basename = $top.tFr52
    place $top.tFr52 \
        -in $top -x 0 -y 790 -width 1130 -relwidth 0 -height 50 -relheight 0 \
        -anchor nw -bordermode ignore 
# add p1 basename = $top.tFr51
    place $top.tFr51 \
        -in $top -x 0 -y 51 -width 1130 -relwidth 0 -height 739 -relheight 0 \
        -anchor nw -bordermode ignore 
# add p1 basename = $top.tFr56
    place $top.tFr56 \
        -in $top -x 0 -y 51 -width 1120 -relwidth 0 -height 735 -relheight 0 \
        -anchor nw -bordermode ignore 
# add p1 basename = $top.tFr50
    place $top.tFr50 \
        -in $top -x 1 -y 1 -width 1130 -relwidth 0 -height 50 -relheight 0 \
        -anchor nw -bordermode ignore 

############# Spot ttt ##############################

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

