#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# ===============================================================
#                     tkEditorDemo1_support.py
# ---------------------------------------------------------------
# Written for users PAGE of Tkinter
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Author: Greg Walters
# Date Created: 2025-10-04 03:20:49
# Version 0.1.2
# Last Updated: 2025-10-05 10:23:29
# ---------------------------------------------------------------
# Copyright © 2025 by G.D. Walters and Designated Geek Software
# ===============================================================
# Purpose:
#    Demonstration program for the tkEditor Metawidget
#
# ===============================================================

# Support module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Oct 03, 2025 08:01:29 AM CDT  platform: Linux
#    Oct 03, 2025 09:02:50 AM CDT  platform: Linux
#    Oct 03, 2025 09:05:36 AM CDT  platform: Linux
#    Oct 03, 2025 10:37:16 AM CDT  platform: Linux
#    Oct 05, 2025 06:17:41 AM CDT  platform: Linux
#    Oct 05, 2025 06:19:51 AM CDT  platform: Linux
#    Oct 05, 2025 07:44:25 AM CDT  platform: Linux
#    Oct 05, 2025 10:48:01 AM CDT  platform: Linux

import sys
import os

import tkEditor1

# import pyScrolledText16

import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
from tkinter import font
import tkinter.messagebox as messagebox
from tkinter import simpledialog
from tkinter import colorchooser
from tkinter.filedialog import (
    askdirectory,
    askopenfilename,
    asksaveasfile,
    asksaveasfilename,
)
from tkinter.simpledialog import askfloat, askinteger, askstring

import tkEditorDemo1

_debug = True  # False to eliminate debug printing from callback functions.
location = tkEditorDemo1._location
programName = "tkEditor Demo #1"
version = "0.1.2"

def main(*args):
    """Main entry point for the application."""
    global root
    root = tk.Tk()
    root.protocol("WM_DELETE_WINDOW", root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = tkEditorDemo1.Toplevel1(_top1)
    startup()
    root.mainloop()

def startup():
    # "Hide" About and Prefs frames
    _w1.frameAbout.lower()
    _w1.framePrefs.lower()

    # Set a global instance of the editor.
    global ed1, ed2

    # Instansiate the editor object into Tab0 frameEd1
    ed1 = tkEditor1.CodeEditor(_w1.frameEd1, indent_width=6)
    ed2 = tkEditor1.CodeEditor(_w1.frameEd2)
    # Set the title of the Toplevel
    _top1.title(f"{programName} - {version}")

    # Get the version of the editor code and the licence
    libVer = ed1.get_version()
    libLic = ed1.get_licence()
    if _debug:
        print(f"{libVer=}")
        print(f"{libLic=}")

    # Housekeeping on the TNotebook
    global current_filename
    current_filename = ""
    _w1.TNotebook1.tab(0, text="Unknown")
    # _w1.TNotebook1.tab(1, state="hidden")
    _w1.TNotebook1.tab(1, text="Unknown")
    _w1.TNotebook1.bind("<<NotebookTabChanged>>", on_NotebookTabChange)
    global totalTabs
    totalTabs = len(_w1.TNotebook1.tabs())
    print(f"{totalTabs=}")
    global currenttab
    currenttab = _w1.TNotebook1.index("current")
    if _debug:
        print(f"{currenttab=}")

    # Load up the defaults into the prefs Frame.

    setupPrefFrame()

    # Load up the ScrolledTextbox info in the About Frame
    about_info = """ Welcome to the tkEditor demo program.
    
    The tkEditor is a Tkinter Metawidget was created by ChatGPT 5.0 from a concept by Greg Walters.  This code was then turned into a Tkinter library which can be easily imported into most any Python/Tkinter program, but was originally created to be used in a PAGE GUI Designer program.

    SOME of the features of the tkEditor Metawidget are:
        * Auto-indent which is configurable by the user (for new text files)
        * Line numbers that scroll with the text.
        * Basic Python syntax highlighting (user configurable)
        * VERY BASIC code folding.

        
    The goal of this project was to create a BASIC text editor that has synced line numbers that requires ABSOLUTELY NO external libraries.  So far the tkEditor1 Metawidget keeps this requirement.  The demo program, currently DOES require at least one external library (for writing the TOML configuration file). Another goal of this project was to provide a usable Metawidget that other PAGE (and Tkinter) programmers can use for education on creation and use of Metawidgets.

    Known Limitations...
      At this time (5 October 2025), the biggest limitation is in the code folding routines and that the code highlighting only works for Python .py files.  Hopefully I can eventually expand this to the possibility of support of .md and .rst (Markdown and Restructured Text) files as well.  But this is in the far future at this point.

      One other limitation is that there is not support to convert Tabs to spaces and that changing the indent amount only works on new files.  Loading an existing file into the editor will NOT apply ANY different indentations.  This is to preserve the format of the existing file.
      

    Still to do ....
    ----------------------

    A few things are currently on my mental list of things to do.  However, I will try to enumerate them here.

        * Configuration file for the program. (Uses TOML)
        * Link the preferences to the library.
        * EVENTUALLY support formatting tags (bold, italic, etc.) for the tk.ScrolledText widget in the About file.  (This file.)
        * Clean up the code in both the tkEditor and demo files.
        * Add ability to have more editors in tabs of the TNotebook.
        *

    For more information, please see the help document (currently unavaiable since it's creation is in process).
    """

    _w1.stAbout.insert(1.0, about_info)
    # ed1.s

def setupPrefFrame():
    # Clear all the TEdit widgets on the Prefs Frame...
    _w1.kwdColorData.set("")
    _w1.stringColorData.set("")
    _w1.commentColourData.set("")
    _w1.LineBgColorData.set("")
    _w1.EditorBgColorData.set("")
    _w1.IndentData.set(4)
    global def_keyword_color, def_string_color, def_comment_color, def_current_line_bg_color, def_editor_bg_color
    global cur_keyword_color, cur_string_color, cur_comment_color, cur_current_line_bg_color, cur_editor_bg_color
    bgcolor = "white"
    def_editor_bg_color = "white"
    def_keyword_color = "#0000ff"
    def_string_color = "#a31515"
    def_comment_color = "#008000"
    def_current_line_bg_color = "#f0f8ff"
    def_current_Editor_bg_color = "white"
    #
    _w1.tlblKeywordColor.configure(background=bgcolor, foreground=def_keyword_color)
    _w1.tlblStringColor.configure(background=bgcolor, foreground=def_string_color)
    _w1.TLblCommentColour.configure(background=bgcolor, foreground=def_comment_color)
    _w1.TlblClineBackground.configure(
        background=def_current_line_bg_color, foreground="black"
    )
    _w1.TlblEditorBgColor.configure(
        background=def_editor_bg_color, foreground=def_string_color
    )
    _w1.KwdLabelTest.set("Test Text")
    _w1.stringLabelTest.set("Test Text")
    _w1.CommentLabelTest.set("Test Text")
    _w1.LineColorLabelTest.set("Test Text")
    _w1.EditorLabelColorTest.set("Test Text")

    _w1.kwdColorData.set(def_keyword_color)
    _w1.stringColorData.set(def_string_color)
    _w1.commentColourData.set(def_comment_color)
    _w1.LineBgColorData.set(def_current_line_bg_color)
    _w1.EditorBgColorData.set(def_editor_bg_color)

    cur_keyword_color = def_keyword_color
    cur_string_color = def_string_color
    cur_comment_color = def_comment_color
    cur_current_line_bg_color = def_current_line_bg_color
    cur_editor_bg_color = def_current_Editor_bg_color

def on_NotebookTabChange(*args):
    # Callback function for TNotebook
    global currenttab
    currenttab = _w1.TNotebook1.index("current")
    if _debug:
        print(f"{currenttab=}")

def on_btnClear(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnClear")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    ed1.clear_editor()

def on_btnExit(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnExit")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    sys.exit()

def on_btnFileNew(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnFileNew")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    global current_filename
    current_filename = ""
    _w1.TNotebook1.tab(currenttab, text="Unknown")
    on_btnClear()

def on_btnFileOpen(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnFileOpen")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    global ed1, ed2, current_filename, basefile, currenttab
    if currenttab == 0:
        editorToUse = ed1
    elif currenttab == 1:
        editorToUse = ed2
    # editorToUse = f"ed{currenttab+1}"
    # print(f"{editorToUse}")
    # editorObject = object(editorToUse)
    basefile = ""
    if _debug:
        print("pyed2a_support.on_btnFileOpen")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    filename = askopenfilename(
        initialdir=location,
        title="Select A File",
        parent=_top1,
        filetypes=(
            ("Python files", "*.py"),
            ("ttd files", "*.ttd"),
            ("Markdown", "*.md"),
            ("RST files", "*.rst"),
            ("text files", "*.txt"),
            ("Any Files", "*.*"),
        ),
    )
    # print(filename)
    if filename != ():
        if filename != "":
            if _debug:
                print(f"{filename}")
            # return filename
            editorToUse.clear_editor()
            editorToUse.load_file(filename)
            current_filename = filename
            basefile = os.path.basename(current_filename)
    _top1.title(f"{programName} - {version} - {basefile}")
    _w1.TNotebook1.tab(currenttab, text=basefile)

def on_btnFileSave(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnFileSave")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    global current_filename, basefile

    contents = ed1.text.get(1.0, END)
    if current_filename == "":
        # ask filename and location
        file_path = asksaveasfilename(
            defaultextension=".txt",
            filetypes=[
                ("Python files", "*.py"),
                ("ttd files", "*.ttd"),
                ("Markdown", "*.md"),
                ("RST files", "*.rst"),
                ("text files", "*.txt"),
                ("Any Files", "*.*"),
            ],
            initialdir=location,  # Optional: set initial directory
            title="Save your file",  # Optional: set dialog title
        )
        if file_path:
            # User selected a file path, now you can write data to it
            with open(file_path, "w") as f:
                f.write(contents)
            if _debug:
                print(f"File saved to: {file_path}")
            basefile = os.path.basename(file_path)
            _top1.title(f"{programName} - {version} - {basefile} - Saved")
            _w1.TNotebook1.tab(0, text=basefile)

        else:
            print("Save operation cancelled.")
    else:
        with open(current_filename, "w") as f:
            f.write(contents)
        if _debug:
            print(f"File Write complete")
    _top1.title(f"{programName} - {version} - {basefile} - Saved")
    _w1.TNotebook1.tab(0, text=basefile)

def write_file(filename, strng):
    with open(filename, "w") as f:
        f.write(strng)

def read_file(filename):
    # ======================================================
    # function read_file()
    # ======================================================
    # Read file, leaving end of lines
    # ======================================================
    with open(filename) as f:
        lines = f.read()
    return lines

def on_bthAbout(*args):
    if _debug:
        print("tkEditorDemo1_support.on_bthAbout")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    _w1.frameAbout.lift()

def on_btnHelp(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnHelp")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    titl = f"{programName}"
    msg = "Sorry, but the help fucntion is still under development."
    parent = _top1
    ico = messagebox.INFO
    messagebox.showinfo(titl, msg, parent=parent, icon=ico)

def on_btnAboutDismiss(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnAboutDismiss")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    _w1.frameAbout.lower()

def on_btnFileSaveAs(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnFileSaveAs")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    current_filename = ""
    contents = ed1.text.get(1.0, END)
    if current_filename == "":
        # ask filename and location
        file_path = asksaveasfilename(
            defaultextension=".txt",
            filetypes=[
                ("Python files", "*.py"),
                ("ttd files", "*.ttd"),
                ("Markdown", "*.md"),
                ("RST files", "*.rst"),
                ("text files", "*.txt"),
                ("Any Files", "*.*"),
            ],
            initialdir=location,  # Optional: set initial directory
            title="Save your file",  # Optional: set dialog title
        )
        if file_path:
            # User selected a file path, now you can write data to it
            with open(file_path, "w") as f:
                f.write(contents)
            if _debug:
                print(f"File saved to: {file_path}")
            basefile = os.path.basename(file_path)
            _top1.title(f"{programName} - {version} - {basefile} - Saved")
            _w1.TNotebook1.tab(0, text=basefile)
        else:
            if _debug:
                print("Save operation cancelled.")
    else:
        with open(current_filename, "w") as f:
            f.write(contents)
        if _debug:
            print(f"File Write complete")
        basefile = os.path.basename(current_filename)
        _top1.title(f"{programName} - {version} - {basefile} - Saved")
        _w1.TNotebook1.tab(0, text=basefile)

def on_btnCommentColour(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnCommentColour")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    global def_keyword_color, def_string_color, def_comment_color, def_current_line_bg_color, def_editor_bg_color
    global cur_keyword_color, cur_string_color, cur_comment_color, cur_current_line_bg_color, cur_editor_bg_color
    choice = colorchooser.askcolor(def_comment_color)
    print(f"{choice=}")

    _w1.commentColourData.set(choice[1])
    _w1.TLblCommentColour.configure(foreground=choice[1])
    cur_comment_color = choice[1]
    # Write to globals and config.toml

def on_btnCurrentLineColour(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnCurrentLineColour")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    global def_keyword_color, def_string_color, def_comment_color, def_current_line_bg_color, def_editor_bg_color
    global cur_keyword_color, cur_string_color, cur_comment_color, cur_current_line_bg_color, cur_editor_bg_color
    choice = colorchooser.askcolor(def_current_line_bg_color)
    print(f"{choice=}")
    _w1.LineBgColorData.set(choice[1])
    _w1.TlblClineBackground.configure(background=choice[1])
    cur_current_line_bg_color = choice[1]
    # Write to globals and config.toml

def on_btnKeywordColour(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnKeywordColour")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()

    global def_keyword_color, def_string_color, def_comment_color, def_current_line_bg_color, def_editor_bg_color
    global cur_keyword_color, cur_string_color, cur_comment_color, cur_current_line_bg_color, cur_editor_bg_color
    choice = colorchooser.askcolor(def_keyword_color)

    print(f"{choice[1]=}")
    _w1.kwdColorData.set(choice[1])
    _w1.tlblKeywordColor.configure(foreground=choice[1])
    cur_keyword_color = choice[1]
    # Write to globals and config.toml

def on_btnPrefs(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnPrefs")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    _w1.framePrefs.lift()

def on_btnStringColour(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnStringColour")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    global def_keyword_color, def_string_color, def_comment_color, def_current_line_bg_color, def_editor_bg_color
    global cur_keyword_color, cur_string_color, cur_comment_color, cur_current_line_bg_color, cur_editor_bg_color
    choice = colorchooser.askcolor(def_string_color)
    print(f"{choice=}")
    _w1.stringColorData.set(choice[1])
    _w1.tlblStringColor.configure(foreground=choice[1])
    cur_string_color = choice[1]
    # Write to globals and config.toml

def on_btnPrefDismiss(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnPrefDismiss")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()
    _w1.framePrefs.lower()

def on_btnPrefsIgnoreChanges(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnPrefsIgnoreChanges")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()

def on_btnPrefsSaveChanges(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnPrefsSaveChanges")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()

def on_btnEditorBGColour(*args):
    if _debug:
        print("tkEditorDemo1_support.on_btnEditorBGColour")
        for arg in args:
            print("    another arg:", arg)
        sys.stdout.flush()

    global def_keyword_color, def_string_color, def_comment_color, def_current_line_bg_color, def_editor_bg_color
    global cur_keyword_color, cur_string_color, cur_comment_color, cur_current_line_bg_color, cur_editor_bg_color
    choice = colorchooser.askcolor(def_editor_bg_color)

    print(f"{choice[1]=}")
    _w1.EditorBgColorData.set(choice[1])
    _w1.TlblEditorBgColor.configure(background=choice[1], foreground="black")
    cur_editor_bg_color = choice[1]
    # Write to globals and config.toml

if __name__ == "__main__":
    tkEditorDemo1.start_up()




